### ISSUE TITLE
Add source user authentication

### ISSUE THREAD

**Issue by zipmedia** [OPENSPHERE-Inc/branch-output#19]
I would like to use user authentication for ingest, but I can't see any options for entering a username and password within the plugin. It would be desirable to extend the UI and functionality, as it is available in the OBS stream settings.
![image](https://github.com/user-attachments/assets/abf62b11-8ce3-4008-9777-504172ae4dab)

**Comment by hanatyan128** [comment]
As you pointed out, this is a missing feature, but it will work if we add an input field. It will be added in the next update.

**Comment by hanatyan128** [comment]
Update released.

**Comment by zipmedia** [comment]
That was amazingly fast! Thanks a lot.
