### ISSUE TITLE
Multiple Audio Tracks

### ISSUE THREAD

**Issue by Jukebox288** [OPENSPHERE-Inc/branch-output#26]
Either I can't find it or there is no option to have multiple audio tracks in the recording file like in a regular OBS recording.

**Comment by Kyanoxia** [comment]
+1 would love to see this available.  A number of people have also asked for this on Source Record: https://github.com/exeldro/obs-source-record/issues/93

**Comment by hanatyan128** [comment]
Integrated multirack audio at release 0.9.14.
https://github.com/OPENSPHERE-Inc/branch-output/releases/tag/0.9.14
