### ISSUE TITLE
Recording save path to follow OBS path variables for dates etc.

### ISSUE THREAD

**Issue by Ashtlind** [OPENSPHERE-Inc/branch-output#27]
Hi,

We are loving this plugin and keep finding new uses for it! It's been a pretty big game changer and saved us a lot.

We would love it if the recording path in the filter could save along side the OBS recording. Our recording path is set to the following for our main recording, this makes nice folders for each year month and day as we do multiple iso recordings and other project files all in there:
/%CCYY/%MM %B/%DD %A/%hh-%mm-%ss%p Stream

So ideally if we could specify for the save path to either allow for the same date variables or to be saved along side the main path like this:
/%CCYY/%MM %B/%DD %A/%hh-%mm-%ss%p ISO

At the moment the recordings seem to just appear in the root directory:
![image](https://github.com/user-attachments/assets/c25fa9b3-d958-45d0-9151-8a9f98647f23)

Thanks heaps!

Any questions let me know

**Comment by hanatyan128** [comment]
Filename formatting feature will be included next release.

**Comment by Ashtlind** [comment]
Thankyou! Look forward to trying this out!

**Comment by Ashtlind** [comment]
This is great @hanatyan128 

The only small issue we are having is that all white spaces are being replaced by underscores. Is there a setting like in the main output page to toggle generating file names with and without spaces?

Thanks so much! All these new features are great, looking forward to trying multitrack audio soon
