### ISSUE TITLE
Resolution issue while streaming

### ISSUE THREAD

**Issue by dremix99** [OPENSPHERE-Inc/branch-output#28]
First off thank you very much for this amazing plugin but I unfortunately have one issue with it.
I have a 4K TV on which I play and stream from which outputs to 1080p on Twitch.
While using Branch Output it always outputs to Twitch on 4K which is impossible to stream on.

I have tried everything, setting base canvas and output canvas to 1080p, enabling all sorts of rescaling outputs, etc...

Unfortunately it still outputs to 4K...

Thank you

**Comment by hanatyan128** [comment]
> First off thank you very much for this amazing plugin but I unfortunately have one issue with it. I have a 4K TV on which I play and stream from which outputs to 1080p on Twitch. While using Branch Output it always outputs to Twitch on 4K which is impossible to stream on.
> 
> I have tried everything, setting base canvas and output canvas to 1080p, enabling all sorts of rescaling outputs, etc...
> 
> Unfortunately it still outputs to 4K...
> 
> Thank you

In other words, am I correct in my understanding that you are capturing in 4K to OBS and have added Branch Output to the video capture input?

I believe this is the case because of the current this plugin specifications (limitations) that it is streamed at the resolution of the input.

I think changing the resolution would be nice to have as a feature, so I'll add it as a todo in a future update.

Another work-around that can be done on the user side right now is to add a Branch Output to the scene. If the canvas size is 1080p, it will be streamed in 1080p.
You can try it if you like.

**Comment by dremix99** [comment]
Thank you for the quick reply. 

Adding Branch Output to the scene does indeed "force" the stream to be at 1080p. 

My only issue with that is it will grab my whole scene including my webcam which I don't want to be included.

What I did before was adding Branch Output to the Game Capture source so that it could only record that and let it grab audio from my entire OBS via Master Track. 
That way I could have my stream set up as normal on Twitch and then have clear and clean clips to use for editing without my webcam on it, twitch chat overlay, discord overlay, etc...

I haven't found a way around this unfortunately, so I might have to wait for a future update that allows the user to "force" Branch Output to stream and record at the desired resolution.

Nevertheless, thank you again

**Comment by hanatyan128** [comment]
> Thank you for the quick reply.
> 
> Adding Branch Output to the scene does indeed "force" the stream to be at 1080p.
> 
> My only issue with that is it will grab my whole scene including my webcam which I don't want to be included.
> 
> What I did before was adding Branch Output to the Game Capture source so that it could only record that and let it grab audio from my entire OBS via Master Track. That way I could have my stream set up as normal on Twitch and then have clear and clean clips to use for editing without my webcam on it, twitch chat overlay, discord overlay, etc...
> 
> I haven't found a way around this unfortunately, so I might have to wait for a future update that allows the user to "force" Branch Output to stream and record at the desired resolution.
> 
> Nevertheless, thank you again

This is another method that I know of that can be added to the previous work-around.

1. Right-click on the target source and select "Copy".

2. Select "Paste (Reference)" into a new scene that you've created separately.

3. Add a Branch Output to the scene that now contains only the target source.

This source is a "reference" and not a duplicate, so it should work perfectly with the original source without conflicting.

It will take some time for the plugin to be updated, so it might be worth a try in the meantime.

**Comment by hanatyan128** [comment]
Changing resolution and scaling filter feature will be integrated in next release.

**Comment by dremix99** [comment]
Thank you very much for the follow up :)
