### ISSUE TITLE
Audio delay ≈ 0.8s

### ISSUE THREAD

**Issue by angeloruggieridj** [OPENSPHERE-Inc/branch-output#29]
I'm using this plugin but when it is activated as filter in a scene with the Custom Audio Source enabled,
the audio compared with the live streaming and the OBS recordings is delayed ≈ 0.8s.

It forces to do further effort in post-production in order to arrange them with the master of all cameras.

How can I remove or decrease this delay?
At the moment is configured as follow:

- Custom Audio Source: enabled
- Source: Master Audio
- Track: Track 1
- Audio Encoder: CoreAudio AAC (I'm on Mac)
- Audio bitrate: None
- Video encoder is Apple VTH264

**Comment by hanatyan128** [comment]
> I'm using this plugin but when it is activated as filter in a scene with the Custom Audio Source enabled, the audio compared with the live streaming and the OBS recordings is delayed ≈ 0.8s.
> 
> It forces to do further effort in post-production in order to arrange them with the master of all cameras.
> 
> How can I remove or decrease this delay? At the moment is configured as follow:
> 
> * Custom Audio Source: enabled
> * Source: Master Audio
> * Track: Track 1
> * Audio Encoder: CoreAudio AAC (I'm on Mac)
> * Audio bitrate: None
> * Video encoder is Apple VTH264

I just have one question to help us understand exactly what is going on and how to fix the plug-in.

"The stream and/or recorded file output by the Branch Output that uses master audio has a gap between the video and the audio themself, and the audio is delayed by about 0.8s relative to the video."

Is this correct?

**Comment by angeloruggieridj** [comment]
Yes, that’s the problem.

**Comment by hanatyan128** [comment]
I pushed quick fix version. (Binay build going on)
https://github.com/OPENSPHERE-Inc/branch-output/releases/tag/0.9.10

Unfortunately I don't have a Mac so please let me know the results if you would like.

**Comment by hanatyan128** [comment]
Tested video (via Branch Output + Master Audio)

https://github.com/user-attachments/assets/4b9f9335-b87c-4f58-bba8-19442180cc18

**Comment by angeloruggieridj** [comment]
I've tested on Mac and latest OBS 30.2.3. It is working!
Thanks for developing this fix as light speed.

We use your plugin in our production line.

**Comment by hanatyan128** [comment]
I re-push with 0.9.11 because lost master track 2~ support since 0.9.10.
https://github.com/OPENSPHERE-Inc/branch-output/releases/tag/0.9.11
