### ISSUE TITLE
Dock is not working

### ISSUE THREAD

**Issue by corruptmane** [OPENSPHERE-Inc/branch-output#32]
So, I confirm that recording itself is working (I'm trying this plugin to replace source-record). But I can't see any data in the dockable window (Branch Output Status). I've tried to switch `interlock` to every existing row there, nothing changed. Also, it'd be good to be able to change template for file naming in the filter itself.

**Comment by hanatyan128** [comment]
> So, I confirm that recording itself is working (I'm trying this plugin to replace source-record). But I can't see any data in the dockable window (Branch Output Status). I've tried to switch `interlock` to every existing row there, nothing changed. Also, it'd be good to be able to change template for file naming in the filter itself.

Let me ask you a few questions to help us understand the situation.

- Does the output itself function just because the dock does not show the status?
- Is it the entire contents of the dock that is not displayed (including the table frame and buttons) or just the text information? Is it possible to take a screenshot for better clarity?
- What is your environment (OS, language, screen resolution, and font magnification if you have it set)?
- If you are using a non-English setting, will reverting the language setting back to English fix it?
- Are you using a custom theme for OBS?　Is it not corrected by reverting to the default (e.g. Yami)?

Also, file naming feature is handled by another issue #27

**Comment by corruptmane** [comment]
- Didn't understand the question. Output works regardless of dock. Attached dock / floating dock / no dock, output works fine. My issue is - I don't understand how to control output flow without rows in the dock table. How can I start/stop/pause it.
- Table frame is there, but no buttons. Screenshot is below
- Artix linux, `en_US.UTF-8` locale, 2 screens (2560x1440 that is recording, and laptop 1920x1080), no font magnification. OBS is from AUR: `[obs-studio-browser](https://aur.archlinux.org/packages/obs-studio-browser)` version 30.2.3-browser-3 to be exact.
- Default theme (`Yami`)

![image](https://github.com/user-attachments/assets/0288e956-131f-4c08-9324-6d0c9aac167e)

**Comment by hanatyan128** [comment]
Seems like there's some kind of bug.
One more question to help me identify and fix the issue: Do you have any UI related plugins installed, like those that modify the scene list or source list functionality?

FYI Workaround to control stop/start: Click eye icon on filter list. Disabled filter doesn't do streaming/recording

**Comment by hanatyan128** [comment]
I pushed quick fix version 0.9.12
https://github.com/OPENSPHERE-Inc/branch-output/releases/tag/0.9.12

Binary build is going on.

Confirmed working on EndeavourOS 
![image](https://github.com/user-attachments/assets/d96dd653-c477-46aa-abd9-b93b75387597)

**Comment by corruptmane** [comment]
I've updated the plugin but the issue is still here. I've got a question, how did you install this plugin in arch-based distro? Because .deb packages are not recommended for install. What I did, I extracted files from .deb package and copied files to `~/.config/obs-studio/plugins/osi-branch-output/`. the .so file is in the `./bin/64bit` directory and locales are in `./data/locale`. It looks like this:

```
~/.config/obs-studio/plugins/osi-branch-output > tree
.
├── bin
│   └── 64bit
│       └── osi-branch-output.so
└── data
    └── locale
        ├── ca-ES.ini
        ├── de-DE.ini
        ├── en-US.ini
        ├── fr-FR.ini
        ├── ja-JP.ini
        ├── ko-KR.ini
        ├── ro-RO.ini
        ├── ru-RU.ini
        ├── uk-UA.ini
        └── zh-CN.ini
```

I've got this layout from all the other plugins that I've installed. For clarity, my installed plugins are:

- source-clone
- source-record
- osi-branch-output
- obs-stroke-glow-shadow
- obs-advanced-masks
- 3d-effect
- gradient-source

None of those plugins are providing UI updates.

**Comment by hanatyan128** [comment]
> I've updated the plugin but the issue is still here. I've got a question, how did you install this plugin in arch-based distro? Because .deb packages are not recommended for install. What I did, I extracted files from .deb package and copied files to `~/.config/obs-studio/plugins/osi-branch-output/`. the .so file is in the `./bin/64bit` directory and locales are in `./data/locale`. It looks like this:
> 
> ```
> ~/.config/obs-studio/plugins/osi-branch-output > tree
> .
> ├── bin
> │   └── 64bit
> │       └── osi-branch-output.so
> └── data
>     └── locale
>         ├── ca-ES.ini
>         ├── de-DE.ini
>         ├── en-US.ini
>         ├── fr-FR.ini
>         ├── ja-JP.ini
>         ├── ko-KR.ini
>         ├── ro-RO.ini
>         ├── ru-RU.ini
>         ├── uk-UA.ini
>         └── zh-CN.ini
> ```

Generaly i placed plugin binary (*.so) in 
/usr/lib/obs-plugins

and locale file is in
/usr/share/obs/[plugin name]/locale

Package is obs-studio-tytan652 in AUR


FYI: You can check plugin's version is up to date via filter's properties.

![image](https://github.com/user-attachments/assets/e6a0bd0d-47b6-4f39-9972-8f0004b3ce0d)

**Comment by hanatyan128** [comment]
We need OBS log to investigate more deeper.
Please add —verbose command line option when start OBS

> 
> Also, if it may help you, I guess `activate all` and `deactivate all` should trigger that "eye" icon in the filters, right? Neither of those buttons doesn't do anything to that filter.

These buttons are depending on list contents so doesn’t work when it’s empty

Reopen issue

**Comment by corruptmane** [comment]
At some point I've clicked eye icon on the filter to disable it, then enabled it again. Then - I clicked `activate all` and `deactivate all` in dock.

I've cleaned logs from video data stream logs: https://pastebin.com/kaQf7wtW
Full log with video data stream logs: https://pastebin.com/6ppHKGVH

**Comment by hanatyan128** [comment]
> At some point I've clicked eye icon on the filter to disable it, then enabled it again. Then - I clicked `activate all` and `deactivate all` in dock.
> 
> I've cleaned logs from video data stream logs: https://pastebin.com/kaQf7wtW Full log with video data stream logs: https://pastebin.com/6ppHKGVH

Mayebe this is CI/CD issue, seems different between local build to GitHub's build
I'll try to fix it but you can also compile from source if you want during meantime.

**Comment by corruptmane** [comment]
> Mayebe this is CI/CD issue, seems different between local build to GitHub's build I'll try to fix it but you can also compile from source if you want during meantime.

What command should I use to build it?

**Comment by corruptmane** [comment]
Ok, I built it using `cmake build .`. It works now, seems it is really CI/CD issue.
