### ISSUE TITLE
OBS lost responding after configuring "Branch Output"'s effect filters settings

### ISSUE THREAD

**Issue by yixinBC** [OPENSPHERE-Inc/branch-output#43]
steps to reproduce:

- OBS version 31.0.0
- install brach-output
- add a camera input source
- add "Branch Output" as effect filters to the source
- edit it's setting.for me, I set "stream_recording" to true,then I tried to change it's output directory.

After those steps,OBS crashed.I have tried restart OBS,but any time when I tried to edit "Branch Output"'s setting, it crashed again.

**Comment by hanatyan128** [comment]
Hello, can you attach crash log ?
It's placed in 
C:\Users\[username]\AppData\Roaming\obs-studio\crashes
(windows case)

Pick one of crashing with branch-output filter.

Also ensure video encoder settings is properly. (nvenc had been changed since OBS 31)
Crashes with ffmpeg are offenly caused by misconfigured video encoder.

**Comment by hanatyan128** [comment]
And, possibly reconfigure of video encoder fixes ffmpeg crash.

**Comment by yixinBC** [comment]
> Hello, can you attach crash log ? It's placed in C:\Users[username]\AppData\Roaming\obs-studio\crashes (windows case)
> 
> Pick one of crashing with branch-output filter.
> 

I checked this folder but it's empty.
![图片](https://github.com/user-attachments/assets/9d102916-55d1-43d4-a33a-aecab0b967c9)

> Crashes with ffmpeg are offenly caused by misconfigured video encoder.
I've changed it before I open this issue.

The situation I encountered was that the program did not respond after performing the above operations, and I am not sure if this can be considered a crash.

**Comment by hanatyan128** [comment]
> > Hello, can you attach crash log ? It's placed in C:\Users[username]\AppData\Roaming\obs-studio\crashes (windows case)
> > Pick one of crashing with branch-output filter.
> 
> I checked this folder but it's empty. ![图片](https://private-user-images.githubusercontent.com/61578883/395765963-9d102916-55d1-43d4-a33a-aecab0b967c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNjU2MjcsIm5iZiI6MTczNDE2NTMyNywicGF0aCI6Ii82MTU3ODg4My8zOTU3NjU5NjMtOWQxMDI5MTYtNTVkMS00M2Q0LWEzM2EtYWVjYWIwYjk2N2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDA4MzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTljMGNmODE1N2MzOTc4MWFlMzFkZGIwNWVhN2JlYzUyMzAwNzRkYmUwOTU1NDI5YzI4ODg2OTMwZTAzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZuyFEiV6S7t32XX7GUf6gc4Xc-E7WfVDZTrM4cUdGn8)
> 
> > Crashes with ffmpeg are offenly caused by misconfigured video encoder.
> 
> I've changed it before I open this issue.
> 
> The situation I encountered was that the program did not respond after performing the above operations, and I am not sure if this can be considered a crash.

Ok, i need obs log to understand what going on at that time.
It's placed C:\Users\[username]\AppData\Roaming\obs-studio\logs

Start OBS with `--verbose` command line option and try to reproduce that OBS freeze.
Please pick up log file that OBS freezing situation.

**Comment by yixinBC** [comment]
[2024-12-14 16-46-59.txt](https://github.com/user-attachments/files/18135168/2024-12-14.16-46-59.txt)

emmm...
I'm sorry.It seems a ffmpeg encoder error?

**Comment by hanatyan128** [comment]
Seems ffmpeg issue, can you choose other video encoder such as NVENC h.264 or x264 ?

Your log says using SVT-AV1 as encoder.

If output starts immediately after launching OBS, start it in safe mode and remove the filter, then restart OBS normal mode.

**Comment by yixinBC** [comment]
> Seems ffmpeg issue, can you choose other video encoder such as NVENC h.264 or x264 ?

Yes,I've switched to NVENC HEVC,and it works well.
I'm deeply sorry for the misunderstanding caused by my previous remarks.
